receivers:

  hostmetrics/system:
    root_path: /hostfs
    collection_interval: 5m
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.logical.count:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      load:

  hostmetrics/disk:
    root_path: /hostfs
    collection_interval: 9m
    scrapers:
      disk:
      filesystem:

  hostmetrics/network:
    root_path: /hostfs
    collection_interval: 120s
    scrapers:
      network:

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: false
        host.arch:
          enabled: true
        host.ip:
          enabled: true
        host.mac:
          enabled: true
        host.cpu.vendor.id:
          enabled: true
        host.cpu.family:
          enabled: true
        host.cpu.model.id:
          enabled: true
        host.cpu.model.name:
          enabled: true
        host.cpu.stepping:
          enabled: true
        host.cpu.cache.l2.size:
          enabled: true
        os.description:
          enabled: true
        os.type:
          enabled: true
  batch:
    send_batch_size: 1000
    timeout: 1s
    send_batch_max_size: 1500

exporters:
  # Exporter to send logs and metrics to Elasticsearch
  elasticsearch/otel:
    endpoints: [ "http://127.0.0.1:8080" ]
    tls:
      insecure: true
    mapping:
      mode: otel

service:
  pipelines:
    metrics/hostmetrics:
      receivers: [hostmetrics/system, hostmetrics/disk, hostmetrics/network]
      processors: [batch, resourcedetection]
      exporters: [elasticsearch/otel]
